import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import homeImg from "../../public/assets/hero.png"
import { useEffect, useState } from "react";
import { supabase } from "@/services/supabaseClient";


export default function Home() {

    const [count, setCount] = useState(0)

    useEffect(()=> {
        async function getDataCount(){
         const {count}= await supabase
            .from("tasks")
            .select("*", {count: "exact", head: true})
          
          setCount(count as number)
        }

        getDataCount()
    },[])
  return (
    <>
      <Head>
        <title>Tarefas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <Image
            className={styles.imageHome}
            src={homeImg}
            alt="Imagem da home"
            priority={true}
          />

          <h1 className={styles.title}>Sistema feito para voce organizar <br/>seus estudos e tarefas</h1>
          

          <div className={styles.containerButtons}>
            <button className={styles.buttons}>
              + {count} posts
            </button>

            <button className={styles.buttons}>
              + 1 mil comentarios
            </button>
          </div>
        </div>
      </main>

    </>
  );
}
