import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import homeImg from "../../public/assets/hero.png"
import { supabase } from "@/services/supabaseClient";
import { GetStaticProps } from "next";

interface HomeProps{
  tasks: number,
  comments: number
}

export default function Home({tasks, comments}: HomeProps) {
  
  return (
    <>
      <Head>
        <title>Tarefas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <Image
            className={styles.imageHome}
            src={homeImg}
            alt="Imagem da home"
            priority={true}
          />

          <h1 className={styles.title}>Sistema feito para voce organizar <br/>seus estudos e tarefas</h1>
          

          <div className={styles.containerButtons}>
            <button className={styles.buttons}>
              + {tasks} posts
            </button>

            <button className={styles.buttons}>
              + {comments} comentarios
            </button>
          </div>
        </div>
      </main>

    </>
  );
}

export const getStaticProps: GetStaticProps = async ()=>{

    const {count: quantityTasks, error: errorTasks} = await supabase
      .from("tasks")
      .select("*", {count: "exact", head:true})
    
    if(errorTasks){
      console.error(errorTasks.message)
    }

    console.log(quantityTasks)

    const {count: quantityComments, error: errorComments} = await supabase
      .from("comments")
      .select("*", {count:"exact", head: true})

    if(errorComments){
      console.error(errorComments.message)
    }
      

    return {
      props: {
        tasks: quantityTasks,
        comments: quantityComments
      },
      revalidate: 60
    }
}
